// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: cloud-template/v1/cloud-template.proto

package mock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTurnoverByNmsAndOfficeWithOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfficeId      int64                  `protobuf:"varint,1,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	CurrentNmId   int64                  `protobuf:"varint,2,opt,name=current_nm_id,json=currentNmId,proto3" json:"current_nm_id,omitempty"` // найдите самый минимальны nm_id
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                                // 1 - 15 000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTurnoverByNmsAndOfficeWithOffsetRequest) Reset() {
	*x = GetTurnoverByNmsAndOfficeWithOffsetRequest{}
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTurnoverByNmsAndOfficeWithOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTurnoverByNmsAndOfficeWithOffsetRequest) ProtoMessage() {}

func (x *GetTurnoverByNmsAndOfficeWithOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTurnoverByNmsAndOfficeWithOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetTurnoverByNmsAndOfficeWithOffsetRequest) Descriptor() ([]byte, []int) {
	return file_cloud_template_v1_cloud_template_proto_rawDescGZIP(), []int{0}
}

func (x *GetTurnoverByNmsAndOfficeWithOffsetRequest) GetOfficeId() int64 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *GetTurnoverByNmsAndOfficeWithOffsetRequest) GetCurrentNmId() int64 {
	if x != nil {
		return x.CurrentNmId
	}
	return 0
}

func (x *GetTurnoverByNmsAndOfficeWithOffsetRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTurnoverByNmsAndOfficeWithOffsetResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Data              []*GoodsTurnover       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // тут будут только те номенклатуры, которые есть в базе. Которых нет, не будет
	OfficeId          int64                  `protobuf:"varint,2,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	NextPredictedNmId int64                  `protobuf:"varint,3,opt,name=next_predicted_nm_id,json=nextPredictedNmId,proto3" json:"next_predicted_nm_id,omitempty"` // следующий вероятный nm_id списка GoodsTurnover
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTurnoverByNmsAndOfficeWithOffsetResponse) Reset() {
	*x = GetTurnoverByNmsAndOfficeWithOffsetResponse{}
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTurnoverByNmsAndOfficeWithOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTurnoverByNmsAndOfficeWithOffsetResponse) ProtoMessage() {}

func (x *GetTurnoverByNmsAndOfficeWithOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTurnoverByNmsAndOfficeWithOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetTurnoverByNmsAndOfficeWithOffsetResponse) Descriptor() ([]byte, []int) {
	return file_cloud_template_v1_cloud_template_proto_rawDescGZIP(), []int{1}
}

func (x *GetTurnoverByNmsAndOfficeWithOffsetResponse) GetData() []*GoodsTurnover {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetTurnoverByNmsAndOfficeWithOffsetResponse) GetOfficeId() int64 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *GetTurnoverByNmsAndOfficeWithOffsetResponse) GetNextPredictedNmId() int64 {
	if x != nil {
		return x.NextPredictedNmId
	}
	return 0
}

type WarmNmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NmIds         []int64                `protobuf:"varint,1,rep,packed,name=nm_ids,json=nmIds,proto3" json:"nm_ids,omitempty"`   // 1 - 15 000 элементов
	OfficeId      int64                  `protobuf:"varint,2,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"` // > 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmNmsRequest) Reset() {
	*x = WarmNmsRequest{}
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmNmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmNmsRequest) ProtoMessage() {}

func (x *WarmNmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmNmsRequest.ProtoReflect.Descriptor instead.
func (*WarmNmsRequest) Descriptor() ([]byte, []int) {
	return file_cloud_template_v1_cloud_template_proto_rawDescGZIP(), []int{2}
}

func (x *WarmNmsRequest) GetNmIds() []int64 {
	if x != nil {
		return x.NmIds
	}
	return nil
}

func (x *WarmNmsRequest) GetOfficeId() int64 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

type WarmNmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmNmsResponse) Reset() {
	*x = WarmNmsResponse{}
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmNmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmNmsResponse) ProtoMessage() {}

func (x *WarmNmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmNmsResponse.ProtoReflect.Descriptor instead.
func (*WarmNmsResponse) Descriptor() ([]byte, []int) {
	return file_cloud_template_v1_cloud_template_proto_rawDescGZIP(), []int{3}
}

type RecalculateTurnoverForOfficeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfficeId      int64                  `protobuf:"varint,1,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"` // > 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecalculateTurnoverForOfficeRequest) Reset() {
	*x = RecalculateTurnoverForOfficeRequest{}
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalculateTurnoverForOfficeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalculateTurnoverForOfficeRequest) ProtoMessage() {}

func (x *RecalculateTurnoverForOfficeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalculateTurnoverForOfficeRequest.ProtoReflect.Descriptor instead.
func (*RecalculateTurnoverForOfficeRequest) Descriptor() ([]byte, []int) {
	return file_cloud_template_v1_cloud_template_proto_rawDescGZIP(), []int{4}
}

func (x *RecalculateTurnoverForOfficeRequest) GetOfficeId() int64 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

type RecalculateTurnoverForOfficeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecalculateTurnoverForOfficeResponse) Reset() {
	*x = RecalculateTurnoverForOfficeResponse{}
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalculateTurnoverForOfficeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalculateTurnoverForOfficeResponse) ProtoMessage() {}

func (x *RecalculateTurnoverForOfficeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalculateTurnoverForOfficeResponse.ProtoReflect.Descriptor instead.
func (*RecalculateTurnoverForOfficeResponse) Descriptor() ([]byte, []int) {
	return file_cloud_template_v1_cloud_template_proto_rawDescGZIP(), []int{5}
}

type GetTurnoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NmIds         []int64                `protobuf:"varint,1,rep,packed,name=nm_ids,json=nmIds,proto3" json:"nm_ids,omitempty"`   // 1 - 15 000 элементов
	OfficeId      int64                  `protobuf:"varint,2,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"` // > 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTurnoverRequest) Reset() {
	*x = GetTurnoverRequest{}
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTurnoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTurnoverRequest) ProtoMessage() {}

func (x *GetTurnoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTurnoverRequest.ProtoReflect.Descriptor instead.
func (*GetTurnoverRequest) Descriptor() ([]byte, []int) {
	return file_cloud_template_v1_cloud_template_proto_rawDescGZIP(), []int{6}
}

func (x *GetTurnoverRequest) GetNmIds() []int64 {
	if x != nil {
		return x.NmIds
	}
	return nil
}

func (x *GetTurnoverRequest) GetOfficeId() int64 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

type GetTurnoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*GoodsTurnover       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // тут будут только те номенклатуры, которые есть в базе. Которых нет, не будет
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTurnoverResponse) Reset() {
	*x = GetTurnoverResponse{}
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTurnoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTurnoverResponse) ProtoMessage() {}

func (x *GetTurnoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTurnoverResponse.ProtoReflect.Descriptor instead.
func (*GetTurnoverResponse) Descriptor() ([]byte, []int) {
	return file_cloud_template_v1_cloud_template_proto_rawDescGZIP(), []int{7}
}

func (x *GetTurnoverResponse) GetData() []*GoodsTurnover {
	if x != nil {
		return x.Data
	}
	return nil
}

type GoodsTurnover struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NmId                int64                  `protobuf:"varint,1,opt,name=nm_id,json=nmId,proto3" json:"nm_id,omitempty"`
	CountOrders         int64                  `protobuf:"varint,2,opt,name=count_orders,json=countOrders,proto3" json:"count_orders,omitempty"`
	QuantityEndPeriod   int64                  `protobuf:"varint,3,opt,name=quantity_end_period,json=quantityEndPeriod,proto3" json:"quantity_end_period,omitempty"`
	QuantityStartPeriod int64                  `protobuf:"varint,4,opt,name=quantity_start_period,json=quantityStartPeriod,proto3" json:"quantity_start_period,omitempty"`
	PeriodDays          int64                  `protobuf:"varint,5,opt,name=period_days,json=periodDays,proto3" json:"period_days,omitempty"`
	TurnoverRate        int64                  `protobuf:"varint,6,opt,name=turnover_rate,json=turnoverRate,proto3" json:"turnover_rate,omitempty"` // оборачиваемость для коэффициента который не удалось высчитать (null) == -1000
	LastUpdate          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	LastUpdateStr       string                 `protobuf:"bytes,8,opt,name=last_update_str,json=lastUpdateStr,proto3" json:"last_update_str,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GoodsTurnover) Reset() {
	*x = GoodsTurnover{}
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsTurnover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsTurnover) ProtoMessage() {}

func (x *GoodsTurnover) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_template_v1_cloud_template_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsTurnover.ProtoReflect.Descriptor instead.
func (*GoodsTurnover) Descriptor() ([]byte, []int) {
	return file_cloud_template_v1_cloud_template_proto_rawDescGZIP(), []int{8}
}

func (x *GoodsTurnover) GetNmId() int64 {
	if x != nil {
		return x.NmId
	}
	return 0
}

func (x *GoodsTurnover) GetCountOrders() int64 {
	if x != nil {
		return x.CountOrders
	}
	return 0
}

func (x *GoodsTurnover) GetQuantityEndPeriod() int64 {
	if x != nil {
		return x.QuantityEndPeriod
	}
	return 0
}

func (x *GoodsTurnover) GetQuantityStartPeriod() int64 {
	if x != nil {
		return x.QuantityStartPeriod
	}
	return 0
}

func (x *GoodsTurnover) GetPeriodDays() int64 {
	if x != nil {
		return x.PeriodDays
	}
	return 0
}

func (x *GoodsTurnover) GetTurnoverRate() int64 {
	if x != nil {
		return x.TurnoverRate
	}
	return 0
}

func (x *GoodsTurnover) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *GoodsTurnover) GetLastUpdateStr() string {
	if x != nil {
		return x.LastUpdateStr
	}
	return ""
}

var File_cloud_template_v1_cloud_template_proto protoreflect.FileDescriptor

const file_cloud_template_v1_cloud_template_proto_rawDesc = "" +
	"\n" +
	"&cloud-template/v1/cloud-template.proto\x12\x11cloud_template.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n" +
	"*GetTurnoverByNmsAndOfficeWithOffsetRequest\x12\x1b\n" +
	"\toffice_id\x18\x01 \x01(\x03R\bofficeId\x12\"\n" +
	"\rcurrent_nm_id\x18\x02 \x01(\x03R\vcurrentNmId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"\xb1\x01\n" +
	"+GetTurnoverByNmsAndOfficeWithOffsetResponse\x124\n" +
	"\x04data\x18\x01 \x03(\v2 .cloud_template.v1.GoodsTurnoverR\x04data\x12\x1b\n" +
	"\toffice_id\x18\x02 \x01(\x03R\bofficeId\x12/\n" +
	"\x14next_predicted_nm_id\x18\x03 \x01(\x03R\x11nextPredictedNmId\"D\n" +
	"\x0eWarmNmsRequest\x12\x15\n" +
	"\x06nm_ids\x18\x01 \x03(\x03R\x05nmIds\x12\x1b\n" +
	"\toffice_id\x18\x02 \x01(\x03R\bofficeId\"\x11\n" +
	"\x0fWarmNmsResponse\"B\n" +
	"#RecalculateTurnoverForOfficeRequest\x12\x1b\n" +
	"\toffice_id\x18\x01 \x01(\x03R\bofficeId\"&\n" +
	"$RecalculateTurnoverForOfficeResponse\"H\n" +
	"\x12GetTurnoverRequest\x12\x15\n" +
	"\x06nm_ids\x18\x01 \x03(\x03R\x05nmIds\x12\x1b\n" +
	"\toffice_id\x18\x02 \x01(\x03R\bofficeId\"K\n" +
	"\x13GetTurnoverResponse\x124\n" +
	"\x04data\x18\x01 \x03(\v2 .cloud_template.v1.GoodsTurnoverR\x04data\"\xd6\x02\n" +
	"\rGoodsTurnover\x12\x13\n" +
	"\x05nm_id\x18\x01 \x01(\x03R\x04nmId\x12!\n" +
	"\fcount_orders\x18\x02 \x01(\x03R\vcountOrders\x12.\n" +
	"\x13quantity_end_period\x18\x03 \x01(\x03R\x11quantityEndPeriod\x122\n" +
	"\x15quantity_start_period\x18\x04 \x01(\x03R\x13quantityStartPeriod\x12\x1f\n" +
	"\vperiod_days\x18\x05 \x01(\x03R\n" +
	"periodDays\x12#\n" +
	"\rturnover_rate\x18\x06 \x01(\x03R\fturnoverRate\x12;\n" +
	"\vlast_update\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\x12&\n" +
	"\x0flast_update_str\x18\b \x01(\tR\rlastUpdateStr2\xff\x03\n" +
	"\x14GoodsTurnoverService\x12\\\n" +
	"\vGetTurnover\x12%.cloud_template.v1.GetTurnoverRequest\x1a&.cloud_template.v1.GetTurnoverResponse\x12\x8f\x01\n" +
	"\x1cRecalculateTurnoverForOffice\x126.cloud_template.v1.RecalculateTurnoverForOfficeRequest\x1a7.cloud_template.v1.RecalculateTurnoverForOfficeResponse\x12P\n" +
	"\aWarmNms\x12!.cloud_template.v1.WarmNmsRequest\x1a\".cloud_template.v1.WarmNmsResponse\x12\xa4\x01\n" +
	"#GetTurnoverByNmsAndOfficeWithOffset\x12=.cloud_template.v1.GetTurnoverByNmsAndOfficeWithOffsetRequest\x1a>.cloud_template.v1.GetTurnoverByNmsAndOfficeWithOffsetResponseBrZpgithub.com/PavelAgarkov/template/github.com/PavelAgarkov/template/proto/github.com/PavelAgarkov/template/v1;mockb\x06proto3"

var (
	file_cloud_template_v1_cloud_template_proto_rawDescOnce sync.Once
	file_cloud_template_v1_cloud_template_proto_rawDescData []byte
)

func file_cloud_template_v1_cloud_template_proto_rawDescGZIP() []byte {
	file_cloud_template_v1_cloud_template_proto_rawDescOnce.Do(func() {
		file_cloud_template_v1_cloud_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_template_v1_cloud_template_proto_rawDesc), len(file_cloud_template_v1_cloud_template_proto_rawDesc)))
	})
	return file_cloud_template_v1_cloud_template_proto_rawDescData
}

var file_cloud_template_v1_cloud_template_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cloud_template_v1_cloud_template_proto_goTypes = []any{
	(*GetTurnoverByNmsAndOfficeWithOffsetRequest)(nil),  // 0: cloud_template.v1.GetTurnoverByNmsAndOfficeWithOffsetRequest
	(*GetTurnoverByNmsAndOfficeWithOffsetResponse)(nil), // 1: cloud_template.v1.GetTurnoverByNmsAndOfficeWithOffsetResponse
	(*WarmNmsRequest)(nil),                              // 2: cloud_template.v1.WarmNmsRequest
	(*WarmNmsResponse)(nil),                             // 3: cloud_template.v1.WarmNmsResponse
	(*RecalculateTurnoverForOfficeRequest)(nil),         // 4: cloud_template.v1.RecalculateTurnoverForOfficeRequest
	(*RecalculateTurnoverForOfficeResponse)(nil),        // 5: cloud_template.v1.RecalculateTurnoverForOfficeResponse
	(*GetTurnoverRequest)(nil),                          // 6: cloud_template.v1.GetTurnoverRequest
	(*GetTurnoverResponse)(nil),                         // 7: cloud_template.v1.GetTurnoverResponse
	(*GoodsTurnover)(nil),                               // 8: cloud_template.v1.GoodsTurnover
	(*timestamppb.Timestamp)(nil),                       // 9: google.protobuf.Timestamp
}
var file_cloud_template_v1_cloud_template_proto_depIdxs = []int32{
	8, // 0: cloud_template.v1.GetTurnoverByNmsAndOfficeWithOffsetResponse.data:type_name -> cloud_template.v1.GoodsTurnover
	8, // 1: cloud_template.v1.GetTurnoverResponse.data:type_name -> cloud_template.v1.GoodsTurnover
	9, // 2: cloud_template.v1.GoodsTurnover.last_update:type_name -> google.protobuf.Timestamp
	6, // 3: cloud_template.v1.GoodsTurnoverService.GetTurnover:input_type -> cloud_template.v1.GetTurnoverRequest
	4, // 4: cloud_template.v1.GoodsTurnoverService.RecalculateTurnoverForOffice:input_type -> cloud_template.v1.RecalculateTurnoverForOfficeRequest
	2, // 5: cloud_template.v1.GoodsTurnoverService.WarmNms:input_type -> cloud_template.v1.WarmNmsRequest
	0, // 6: cloud_template.v1.GoodsTurnoverService.GetTurnoverByNmsAndOfficeWithOffset:input_type -> cloud_template.v1.GetTurnoverByNmsAndOfficeWithOffsetRequest
	7, // 7: cloud_template.v1.GoodsTurnoverService.GetTurnover:output_type -> cloud_template.v1.GetTurnoverResponse
	5, // 8: cloud_template.v1.GoodsTurnoverService.RecalculateTurnoverForOffice:output_type -> cloud_template.v1.RecalculateTurnoverForOfficeResponse
	3, // 9: cloud_template.v1.GoodsTurnoverService.WarmNms:output_type -> cloud_template.v1.WarmNmsResponse
	1, // 10: cloud_template.v1.GoodsTurnoverService.GetTurnoverByNmsAndOfficeWithOffset:output_type -> cloud_template.v1.GetTurnoverByNmsAndOfficeWithOffsetResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cloud_template_v1_cloud_template_proto_init() }
func file_cloud_template_v1_cloud_template_proto_init() {
	if File_cloud_template_v1_cloud_template_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_template_v1_cloud_template_proto_rawDesc), len(file_cloud_template_v1_cloud_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_template_v1_cloud_template_proto_goTypes,
		DependencyIndexes: file_cloud_template_v1_cloud_template_proto_depIdxs,
		MessageInfos:      file_cloud_template_v1_cloud_template_proto_msgTypes,
	}.Build()
	File_cloud_template_v1_cloud_template_proto = out.File
	file_cloud_template_v1_cloud_template_proto_goTypes = nil
	file_cloud_template_v1_cloud_template_proto_depIdxs = nil
}
