// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.31.1
// source: cloud-template/v1/cloud-template.proto

package mock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	GoodsTurnoverService_GetTurnover_FullMethodName                         = "/cloud_template.v1.GoodsTurnoverService/GetTurnover"
	GoodsTurnoverService_RecalculateTurnoverForOffice_FullMethodName        = "/cloud_template.v1.GoodsTurnoverService/RecalculateTurnoverForOffice"
	GoodsTurnoverService_WarmNms_FullMethodName                             = "/cloud_template.v1.GoodsTurnoverService/WarmNms"
	GoodsTurnoverService_GetTurnoverByNmsAndOfficeWithOffset_FullMethodName = "/cloud_template.v1.GoodsTurnoverService/GetTurnoverByNmsAndOfficeWithOffset"
)

// GoodsTurnoverServiceClient is the client API for GoodsTurnoverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsTurnoverServiceClient interface {
	// Получить оборачиваемость товаров по офису и набору номенклатур
	GetTurnover(ctx context.Context, in *GetTurnoverRequest, opts ...grpc.CallOption) (*GetTurnoverResponse, error)
	// Пересчитать оборачиваемость товаров по всему офису и прогреть по ним кеш
	RecalculateTurnoverForOffice(ctx context.Context, in *RecalculateTurnoverForOfficeRequest, opts ...grpc.CallOption) (*RecalculateTurnoverForOfficeResponse, error)
	// Прогреть кеш оборачиваемости товаров по офису и набору номенклатур
	WarmNms(ctx context.Context, in *WarmNmsRequest, opts ...grpc.CallOption) (*WarmNmsResponse, error)
	// Получить список по переданному минимальному nm_id батчем со смещением
	GetTurnoverByNmsAndOfficeWithOffset(ctx context.Context, in *GetTurnoverByNmsAndOfficeWithOffsetRequest, opts ...grpc.CallOption) (*GetTurnoverByNmsAndOfficeWithOffsetResponse, error)
}

type goodsTurnoverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsTurnoverServiceClient(cc grpc.ClientConnInterface) GoodsTurnoverServiceClient {
	return &goodsTurnoverServiceClient{cc}
}

func (c *goodsTurnoverServiceClient) GetTurnover(ctx context.Context, in *GetTurnoverRequest, opts ...grpc.CallOption) (*GetTurnoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTurnoverResponse)
	err := c.cc.Invoke(ctx, GoodsTurnoverService_GetTurnover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsTurnoverServiceClient) RecalculateTurnoverForOffice(ctx context.Context, in *RecalculateTurnoverForOfficeRequest, opts ...grpc.CallOption) (*RecalculateTurnoverForOfficeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecalculateTurnoverForOfficeResponse)
	err := c.cc.Invoke(ctx, GoodsTurnoverService_RecalculateTurnoverForOffice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsTurnoverServiceClient) WarmNms(ctx context.Context, in *WarmNmsRequest, opts ...grpc.CallOption) (*WarmNmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmNmsResponse)
	err := c.cc.Invoke(ctx, GoodsTurnoverService_WarmNms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsTurnoverServiceClient) GetTurnoverByNmsAndOfficeWithOffset(ctx context.Context, in *GetTurnoverByNmsAndOfficeWithOffsetRequest, opts ...grpc.CallOption) (*GetTurnoverByNmsAndOfficeWithOffsetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTurnoverByNmsAndOfficeWithOffsetResponse)
	err := c.cc.Invoke(ctx, GoodsTurnoverService_GetTurnoverByNmsAndOfficeWithOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsTurnoverServiceServer is the server API for GoodsTurnoverService service.
// All implementations must embed UnimplementedGoodsTurnoverServiceServer
// for forward compatibility
type GoodsTurnoverServiceServer interface {
	// Получить оборачиваемость товаров по офису и набору номенклатур
	GetTurnover(context.Context, *GetTurnoverRequest) (*GetTurnoverResponse, error)
	// Пересчитать оборачиваемость товаров по всему офису и прогреть по ним кеш
	RecalculateTurnoverForOffice(context.Context, *RecalculateTurnoverForOfficeRequest) (*RecalculateTurnoverForOfficeResponse, error)
	// Прогреть кеш оборачиваемости товаров по офису и набору номенклатур
	WarmNms(context.Context, *WarmNmsRequest) (*WarmNmsResponse, error)
	// Получить список по переданному минимальному nm_id батчем со смещением
	GetTurnoverByNmsAndOfficeWithOffset(context.Context, *GetTurnoverByNmsAndOfficeWithOffsetRequest) (*GetTurnoverByNmsAndOfficeWithOffsetResponse, error)
	mustEmbedUnimplementedGoodsTurnoverServiceServer()
}

// UnimplementedGoodsTurnoverServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoodsTurnoverServiceServer struct {
}

func (UnimplementedGoodsTurnoverServiceServer) GetTurnover(context.Context, *GetTurnoverRequest) (*GetTurnoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTurnover not implemented")
}
func (UnimplementedGoodsTurnoverServiceServer) RecalculateTurnoverForOffice(context.Context, *RecalculateTurnoverForOfficeRequest) (*RecalculateTurnoverForOfficeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecalculateTurnoverForOffice not implemented")
}
func (UnimplementedGoodsTurnoverServiceServer) WarmNms(context.Context, *WarmNmsRequest) (*WarmNmsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WarmNms not implemented")
}
func (UnimplementedGoodsTurnoverServiceServer) GetTurnoverByNmsAndOfficeWithOffset(context.Context, *GetTurnoverByNmsAndOfficeWithOffsetRequest) (*GetTurnoverByNmsAndOfficeWithOffsetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTurnoverByNmsAndOfficeWithOffset not implemented")
}
func (UnimplementedGoodsTurnoverServiceServer) mustEmbedUnimplementedGoodsTurnoverServiceServer() {}

// UnsafeGoodsTurnoverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsTurnoverServiceServer will
// result in compilation errors.
type UnsafeGoodsTurnoverServiceServer interface {
	mustEmbedUnimplementedGoodsTurnoverServiceServer()
}

func RegisterGoodsTurnoverServiceServer(s grpc.ServiceRegistrar, srv GoodsTurnoverServiceServer) {
	s.RegisterService(&GoodsTurnoverService_ServiceDesc, srv)
}

func _GoodsTurnoverService_GetTurnover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTurnoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsTurnoverServiceServer).GetTurnover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsTurnoverService_GetTurnover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsTurnoverServiceServer).GetTurnover(ctx, req.(*GetTurnoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsTurnoverService_RecalculateTurnoverForOffice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecalculateTurnoverForOfficeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsTurnoverServiceServer).RecalculateTurnoverForOffice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsTurnoverService_RecalculateTurnoverForOffice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsTurnoverServiceServer).RecalculateTurnoverForOffice(ctx, req.(*RecalculateTurnoverForOfficeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsTurnoverService_WarmNms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarmNmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsTurnoverServiceServer).WarmNms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsTurnoverService_WarmNms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsTurnoverServiceServer).WarmNms(ctx, req.(*WarmNmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsTurnoverService_GetTurnoverByNmsAndOfficeWithOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTurnoverByNmsAndOfficeWithOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsTurnoverServiceServer).GetTurnoverByNmsAndOfficeWithOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsTurnoverService_GetTurnoverByNmsAndOfficeWithOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsTurnoverServiceServer).GetTurnoverByNmsAndOfficeWithOffset(ctx, req.(*GetTurnoverByNmsAndOfficeWithOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsTurnoverService_ServiceDesc is the grpc.ServiceDesc for GoodsTurnoverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsTurnoverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud_template.v1.GoodsTurnoverService",
	HandlerType: (*GoodsTurnoverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTurnover",
			Handler:    _GoodsTurnoverService_GetTurnover_Handler,
		},
		{
			MethodName: "RecalculateTurnoverForOffice",
			Handler:    _GoodsTurnoverService_RecalculateTurnoverForOffice_Handler,
		},
		{
			MethodName: "WarmNms",
			Handler:    _GoodsTurnoverService_WarmNms_Handler,
		},
		{
			MethodName: "GetTurnoverByNmsAndOfficeWithOffset",
			Handler:    _GoodsTurnoverService_GetTurnoverByNmsAndOfficeWithOffset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud-template/v1/cloud-template.proto",
}
