// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: badger_interface/v1/service/badger.proto

package mock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Where struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Where) Reset() {
	*x = Where{}
	mi := &file_badger_interface_v1_service_badger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Where) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Where) ProtoMessage() {}

func (x *Where) ProtoReflect() protoreflect.Message {
	mi := &file_badger_interface_v1_service_badger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Where.ProtoReflect.Descriptor instead.
func (*Where) Descriptor() ([]byte, []int) {
	return file_badger_interface_v1_service_badger_proto_rawDescGZIP(), []int{0}
}

func (x *Where) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Where) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Builder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Table         string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Builder) Reset() {
	*x = Builder{}
	mi := &file_badger_interface_v1_service_badger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Builder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Builder) ProtoMessage() {}

func (x *Builder) ProtoReflect() protoreflect.Message {
	mi := &file_badger_interface_v1_service_badger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Builder.ProtoReflect.Descriptor instead.
func (*Builder) Descriptor() ([]byte, []int) {
	return file_badger_interface_v1_service_badger_proto_rawDescGZIP(), []int{1}
}

func (x *Builder) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Builder) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Builder) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builder       *Builder               `protobuf:"bytes,1,opt,name=builder,proto3" json:"builder,omitempty"`
	WhereIs       []*Where               `protobuf:"bytes,2,rep,name=where_is,json=whereIs,proto3" json:"where_is,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_badger_interface_v1_service_badger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_badger_interface_v1_service_badger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_badger_interface_v1_service_badger_proto_rawDescGZIP(), []int{2}
}

func (x *Query) GetBuilder() *Builder {
	if x != nil {
		return x.Builder
	}
	return nil
}

func (x *Query) GetWhereIs() []*Where {
	if x != nil {
		return x.WhereIs
	}
	return nil
}

type BuildQueryBadgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildQueryBadgerRequest) Reset() {
	*x = BuildQueryBadgerRequest{}
	mi := &file_badger_interface_v1_service_badger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildQueryBadgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildQueryBadgerRequest) ProtoMessage() {}

func (x *BuildQueryBadgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badger_interface_v1_service_badger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildQueryBadgerRequest.ProtoReflect.Descriptor instead.
func (*BuildQueryBadgerRequest) Descriptor() ([]byte, []int) {
	return file_badger_interface_v1_service_badger_proto_rawDescGZIP(), []int{3}
}

func (x *BuildQueryBadgerRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type BuildQueryBadgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    []string               `protobuf:"bytes,1,rep,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildQueryBadgeResponse) Reset() {
	*x = BuildQueryBadgeResponse{}
	mi := &file_badger_interface_v1_service_badger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildQueryBadgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildQueryBadgeResponse) ProtoMessage() {}

func (x *BuildQueryBadgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badger_interface_v1_service_badger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildQueryBadgeResponse.ProtoReflect.Descriptor instead.
func (*BuildQueryBadgeResponse) Descriptor() ([]byte, []int) {
	return file_badger_interface_v1_service_badger_proto_rawDescGZIP(), []int{4}
}

func (x *BuildQueryBadgeResponse) GetResultJson() []string {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

var File_badger_interface_v1_service_badger_proto protoreflect.FileDescriptor

const file_badger_interface_v1_service_badger_proto_rawDesc = "" +
	"\n" +
	"(badger_interface/v1/service/badger.proto\x12\x13badger_interface.v1\"/\n" +
	"\x05Where\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"U\n" +
	"\abuilder\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\"v\n" +
	"\x05query\x126\n" +
	"\abuilder\x18\x01 \x01(\v2\x1c.badger_interface.v1.builderR\abuilder\x125\n" +
	"\bwhere_is\x18\x02 \x03(\v2\x1a.badger_interface.v1.WhereR\awhereIs\"K\n" +
	"\x17BuildQueryBadgerRequest\x120\n" +
	"\x05query\x18\x01 \x01(\v2\x1a.badger_interface.v1.queryR\x05query\":\n" +
	"\x17BuildQueryBadgeResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x03(\tR\n" +
	"resultJson2\x7f\n" +
	"\rBadgerService\x12n\n" +
	"\x10BuildQueryBadger\x12,.badger_interface.v1.BuildQueryBadgerRequest\x1a,.badger_interface.v1.BuildQueryBadgeResponseBYZWgitlab.wildberries.ru/whs-ai/whs-ai/badger-interface/pkg/proto/badger-interface/v1;mockb\x06proto3"

var (
	file_badger_interface_v1_service_badger_proto_rawDescOnce sync.Once
	file_badger_interface_v1_service_badger_proto_rawDescData []byte
)

func file_badger_interface_v1_service_badger_proto_rawDescGZIP() []byte {
	file_badger_interface_v1_service_badger_proto_rawDescOnce.Do(func() {
		file_badger_interface_v1_service_badger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_badger_interface_v1_service_badger_proto_rawDesc), len(file_badger_interface_v1_service_badger_proto_rawDesc)))
	})
	return file_badger_interface_v1_service_badger_proto_rawDescData
}

var file_badger_interface_v1_service_badger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_badger_interface_v1_service_badger_proto_goTypes = []any{
	(*Where)(nil),                   // 0: badger_interface.v1.Where
	(*Builder)(nil),                 // 1: badger_interface.v1.builder
	(*Query)(nil),                   // 2: badger_interface.v1.query
	(*BuildQueryBadgerRequest)(nil), // 3: badger_interface.v1.BuildQueryBadgerRequest
	(*BuildQueryBadgeResponse)(nil), // 4: badger_interface.v1.BuildQueryBadgeResponse
}
var file_badger_interface_v1_service_badger_proto_depIdxs = []int32{
	1, // 0: badger_interface.v1.query.builder:type_name -> badger_interface.v1.builder
	0, // 1: badger_interface.v1.query.where_is:type_name -> badger_interface.v1.Where
	2, // 2: badger_interface.v1.BuildQueryBadgerRequest.query:type_name -> badger_interface.v1.query
	3, // 3: badger_interface.v1.BadgerService.BuildQueryBadger:input_type -> badger_interface.v1.BuildQueryBadgerRequest
	4, // 4: badger_interface.v1.BadgerService.BuildQueryBadger:output_type -> badger_interface.v1.BuildQueryBadgeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_badger_interface_v1_service_badger_proto_init() }
func file_badger_interface_v1_service_badger_proto_init() {
	if File_badger_interface_v1_service_badger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_badger_interface_v1_service_badger_proto_rawDesc), len(file_badger_interface_v1_service_badger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_badger_interface_v1_service_badger_proto_goTypes,
		DependencyIndexes: file_badger_interface_v1_service_badger_proto_depIdxs,
		MessageInfos:      file_badger_interface_v1_service_badger_proto_msgTypes,
	}.Build()
	File_badger_interface_v1_service_badger_proto = out.File
	file_badger_interface_v1_service_badger_proto_goTypes = nil
	file_badger_interface_v1_service_badger_proto_depIdxs = nil
}
