// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.31.1
// source: badger_interface/v1/service/badger.proto

package mock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	BadgerService_BuildQueryBadger_FullMethodName = "/badger_interface.v1.BadgerService/BuildQueryBadger"
)

// BadgerServiceClient is the client API for BadgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BadgerServiceClient interface {
	BuildQueryBadger(ctx context.Context, in *BuildQueryBadgerRequest, opts ...grpc.CallOption) (*BuildQueryBadgeResponse, error)
}

type badgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadgerServiceClient(cc grpc.ClientConnInterface) BadgerServiceClient {
	return &badgerServiceClient{cc}
}

func (c *badgerServiceClient) BuildQueryBadger(ctx context.Context, in *BuildQueryBadgerRequest, opts ...grpc.CallOption) (*BuildQueryBadgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildQueryBadgeResponse)
	err := c.cc.Invoke(ctx, BadgerService_BuildQueryBadger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadgerServiceServer is the server API for BadgerService service.
// All implementations must embed UnimplementedBadgerServiceServer
// for forward compatibility
type BadgerServiceServer interface {
	BuildQueryBadger(context.Context, *BuildQueryBadgerRequest) (*BuildQueryBadgeResponse, error)
	mustEmbedUnimplementedBadgerServiceServer()
}

// UnimplementedBadgerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBadgerServiceServer struct {
}

func (UnimplementedBadgerServiceServer) BuildQueryBadger(context.Context, *BuildQueryBadgerRequest) (*BuildQueryBadgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildQueryBadger not implemented")
}
func (UnimplementedBadgerServiceServer) mustEmbedUnimplementedBadgerServiceServer() {}

// UnsafeBadgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadgerServiceServer will
// result in compilation errors.
type UnsafeBadgerServiceServer interface {
	mustEmbedUnimplementedBadgerServiceServer()
}

func RegisterBadgerServiceServer(s grpc.ServiceRegistrar, srv BadgerServiceServer) {
	s.RegisterService(&BadgerService_ServiceDesc, srv)
}

func _BadgerService_BuildQueryBadger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildQueryBadgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadgerServiceServer).BuildQueryBadger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadgerService_BuildQueryBadger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadgerServiceServer).BuildQueryBadger(ctx, req.(*BuildQueryBadgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadgerService_ServiceDesc is the grpc.ServiceDesc for BadgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "badger_interface.v1.BadgerService",
	HandlerType: (*BadgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildQueryBadger",
			Handler:    _BadgerService_BuildQueryBadger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "badger_interface/v1/service/badger.proto",
}
